### ISSUE TITLE
Focusing a textfield inside a PortalEntry located inside a ListView should not make the listview scroll

### ISSUE THREAD

**Issue by rrousselGit** [fzyzcjy/flutter_portal#20]
```dart
ListView(
  children:  [
    PortalEntry(
      portal: TextField(),
    )
  ]
)

**Comment by venkatd** [comment]
@rrousselGit like you said earlier, I'm pretty confident this bug is the same as #21. The code that triggers scrolling is deep inside EditableText right here: 

https://github.com/flutter/flutter/blob/24c62662309b403c422a0a67a110b1534a2c9fb5/packages/flutter/lib/src/widgets/editable_text.dart#L2327

And this is called throughout EditableText.

The exact line that runs the scroll behavior is here (confirmed that commenting this line out stops the auto-scrolling):

https://github.com/flutter/flutter/blob/24c62662309b403c422a0a67a110b1534a2c9fb5/packages/flutter/lib/src/widgets/editable_text.dart#L2159-L2163

And this logic scrolls to the blinking cursor if it's not visible on the screen. I haven't confirmed 100% but I'm pretty sure that this logic thinks the cursor is somewhere else due to the same portal bug in #21 where it thinks the clicks are somewhere else.

**Comment by rrousselGit** [comment]
I am not sure about the relation with #21, as clicks are working properly

**Comment by venkatd** [comment]
Ah good point. It seems like the code in EditableText is saying "if the cursor is not in view, scroll to the cursor" so the expected behavior would be "do nothing" because the cursor is already in view.
