### ISSUE TITLE
Enhance documentations (in `README.md` and code comments) and CI/codecov

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_portal#49]
After #44, the README.md as well as code comments seem a bit outdated. Maybe we should update it before we can release a new version.

- [x] update README
- [x] update code comments
- [x] #52
- [x] ci
- [x] codecov

Also related

* https://github.com/rrousselGit/flutter_portal/issues/22

@creativecreatorormaybenot

**Comment by creativecreatorormaybenot** [comment]
Regarding the three points:

* Update README
-> I feel like it generally needs to be updated in general, e.g. the "[Call for maintainer](https://github.com/rrousselGit/flutter_portal#call-for-maintainer)"  
The other sections just need to be updated with the concepts I explained at the bottom of the README (the examples etc.)

* Update code comments
-> I forgot to remove [a todo comment](https://github.com/rrousselGit/flutter_portal/blob/144993c74bc3507a9eb8e64dab50f6e3b91e5f11/lib/src/portal_target.dart#L15) but otherwise I updated all the comments I felt are relevant.

* Migration guide
-> I think I could write one. If you want to do it, you can also do it - just lmk what you think.

**Comment by fzyzcjy** [comment]
> I feel like it generally needs to be updated in general, e.g. the "[Call for maintainer](https://github.com/rrousselGit/flutter_portal#call-for-maintainer)"
The other sections just need to be updated with the concepts I explained at the bottom of the README (the examples etc.)

Agree. I will probably replace that section with a paragraph mentioning it is @rrousselGit who creates this package after he [transfers the github repo](https://github.com/rrousselGit/flutter_portal/issues/40#issuecomment-1061806027) to me. Since now it is still his repo and sounds not that reasonable to remove his call for maintainer.

> I forgot to remove [a todo comment](https://github.com/rrousselGit/flutter_portal/blob/144993c74bc3507a9eb8e64dab50f6e3b91e5f11/lib/src/portal_target.dart#L15) but otherwise I updated all the comments I felt are relevant.

Comment removed.

> I think I could write one. If you want to do it, you can also do it - just lmk what you think.

Looking forward to your PR :)
